# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TimeKeeper
                                 A QGIS plugin
 This plugin keeps time for an annotation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-21
        copyright            : (C) 2022 by iMerit
        email                : winston.h@imerit.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TimeKeeper class from file TimeKeeper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .time_keeper import TimeKeeper

    return TimeKeeper(iface)
